#+TITLE: README.org
#+AUTHOR: Laluxx
#+DATE: [2024-11-25]
#+OPTIONS: toc:2

#+begin_quote
This is my dwm, there are many like it, but this one is mine... 
#+end_quote

* TODO Grid [0/1]
It will be similar to the ps3 menu.
- [ ] The main 9 tags will be adjacent horizontaly to each other.
- [ ] Then each tag can have virtually infinite inner tags that will be vertically connected and use vertical animations.
- [ ] S-n or S-<down> to go to the next inner tag or S-C-1..9
- [ ] This will make sure that the animations are always correct

* TODO Lock cursor to window [0/5]
- [ ] Lock the cursor to a window in the current tag.
- [ ] cursor can't exit the locked window geometry.
- [ ] custom border of the locked window: change it's size, color, animation.
- [ ] Each tag can have only one locked window,
- [ ] When switching tag if there is a locked window in the tag you are goint to, make sure the cursor warps at the center of the locked window automatically.

* Borders [0/2]
- [ ] Support gradient and animated borders.
- [ ] Custom color, cornerd radius, borderpx, animation, depending on the layout of the window.

* Urgent support [0/2]
- [ ] Make the urgent window flash the border clor with red.
- [ ] Automaticaly switch to the urgent window.

* Layouts [0/2]
- [ ] [[https://wiki.hyprland.org/Configuring/Dwindle-Layout/][Dwindle]] layout that behaves exactly to default hyprland
- [ ] LATER More layouts... (implement them in guile-scheme)

* TODO Lisp [0/3]
like [[https://awesomewm.org][awesome]] wm provide macros to draw rectangles and interact with them,
so you can create your hown widgets like bars, calendars, menus, etc..
Expose as much as possible of the C internals.
Ideally you should be able to call any C function from lisp
and any lisp function from  C
- [ ] Call any lisp function from C
- [ ] Call any C function from lisp.
- [ ] Guile.

* TODO Unclutter and open emacs
A function to send all the clients to their tag and then open emacs in the current tag 
- [ ]  󰊕 dow_emacs()              Function. [0/1]
  - [ ] 󰊕 delete_other_windows()  Function.



